services:
    db:
        image: postgres:15
        restart: always
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend

    feedback:
        image: spring/feedback:latest
        restart: always
        ports:
            - "8080:8080"
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    db-data:
